-- !Ups
CREATE TABLE "USER" (
  "ID" UUID PRIMARY KEY,
  "EMAIL" VARCHAR(255) UNIQUE NOT NULL,
  "NAME" VARCHAR(255) NOT NULL,
  "PASSWORD" VARCHAR(50) NOT NULL,
  "KIND" VARCHAR(15) NOT NULL
);

CREATE TABLE "BUSINESS" (
  "ID" UUID PRIMARY KEY,
  "OWNER" UUID REFERENCES "USER"("ID") ON DELETE CASCADE,
  "NAME" VARCHAR(255) NOT NULL
);

CREATE TABLE "PRODUCT" (
  "ID" UUID PRIMARY KEY,
  "ID_BUSINESS" UUID REFERENCES "BUSINESS"("ID") ON DELETE CASCADE,
  "NAME" VARCHAR(255) NOT NULL,
  "DESCRIPTION" TEXT NOT NULL,
  "PRICE" DECIMAL(10, 2) NOT NULL,
  "STOCK" BIGINT NOT NULL,
  "IS_HIDDEN" BOOLEAN NOT NULL
);

CREATE TABLE "TRANSACTION" (
  "ID" UUID PRIMARY KEY,
  "ID_CUSTOMER" UUID REFERENCES "USER"("ID") ON DELETE CASCADE,
  "COMPLETED" BOOLEAN NOT NULL,
  "DATE_COMPLETED" TIMESTAMP NOT NULL
);

CREATE TABLE "ORDER" (
  "ID" UUID PRIMARY KEY,
  "ID_TRANSACTION" UUID REFERENCES "TRANSACTION"("ID") ON DELETE CASCADE,
  "ID_PRODUCT" UUID REFERENCES "PRODUCT"("ID") ON DELETE CASCADE,
  "QUANTITY" BIGINT NOT NULL
);

CREATE TABLE "REVIEW" (
  "ID" UUID PRIMARY KEY,
  "ID_USER" UUID REFERENCES "USER"("ID") ON DELETE CASCADE,
  "ID_PRODUCT" UUID REFERENCES "PRODUCT"("ID") ON DELETE CASCADE,
  "LIKED" BOOLEAN,
  "DESCRIPTION" TEXT
);

-- !Downs

DROP TABLE "REVIEW";
DROP TABLE "ORDER";
DROP TABLE "TRANSACTION";
DROP TABLE "PRODUCT";
DROP TABLE "BUSINESS";
DROP TABLE "USER";
